//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Recurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dominio.Recurso.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} invalido!.
        /// </summary>
        public static string CAMPO_X0_INVALIDO {
            get {
                return ResourceManager.GetString("CAMPO_X0_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suas credenciais estão incorretas..
        /// </summary>
        public static string CREDENCIAIS_INCORRETAS {
            get {
                return ResourceManager.GetString("CREDENCIAIS_INCORRETAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados inválidos!.
        /// </summary>
        public static string DADOS_INVALIDOS {
            get {
                return ResourceManager.GetString("DADOS_INVALIDOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario não encontrado!.
        /// </summary>
        public static string DADOS_NAO_ECONTRADOS {
            get {
                return ResourceManager.GetString("DADOS_NAO_ECONTRADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados não informados!.
        /// </summary>
        public static string DADOS_NAO_INFORMADOS {
            get {
                return ResourceManager.GetString("DADOS_NAO_INFORMADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O {0} já está cadastrado no sistema!.
        /// </summary>
        public static string O_X0_INFORMADO_JA_ESTA_CADASTRADO_NO_SISTEMA {
            get {
                return ResourceManager.GetString("O_X0_INFORMADO_JA_ESTA_CADASTRADO_NO_SISTEMA", resourceCulture);
            }
        }
    }
}
